# Generated by Django 6.0 on 2026-01-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otzivi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.RemoveField(
            model_name='review',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='review',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='review',
            name='show_on_site',
            field=models.BooleanField(default=False, verbose_name='Показывать на сайте'),
        ),
        migrations.AlterField(
            model_name='review',
            name='email',
            field=models.CharField(max_length=200, verbose_name='Email'),
        ),
    ]
