# Generated by Django 5.2.10 on 2026-01-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otzivi', '0002_alter_review_options_remove_review_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='email',
            field=models.CharField(default='email', max_length=200, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='review',
            name='full_name',
            field=models.CharField(default='ФИО', max_length=200, verbose_name='ФИО'),
        ),
    ]
